# Generated by Django 3.1.7 on 2021-03-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='receiver',
        ),
    ]
