# Generated by Django 3.1.7 on 2021-03-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_auto_20210311_1325'),
        ('notification', '0002_auto_20210311_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_ques', to='question.question'),
        ),
    ]
