# Generated by Django 3.1.7 on 2021-03-09 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0010_auto_20210309_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like',
        ),
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, null=True, related_name='answer_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
