# Generated by Django 3.1.7 on 2021-03-09 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0011_auto_20210309_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default='Like', max_length=10)),
                ('ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_like', to='question.answer')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
