# Generated by Django 3.1.7 on 2021-03-09 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0012_auto_20210309_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, related_name='answer_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
