# Generated by Django 3.1.7 on 2021-03-09 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0013_auto_20210309_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
