# Generated by Django 3.1.7 on 2021-03-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20210309_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='views',
            new_name='like',
        ),
    ]
