# Generated by Django 3.1.7 on 2021-03-11 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0018_auto_20210310_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, related_name='question_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
